=== holodeck-b2b/Holodeck-B2B/modules/holodeckb2b-certmanager/src/main/resources/xsd/hb2b-certmanager-cfg.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 The Holodeck B2B Team, Sander Fieten

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://holodeck-b2b.org/schemas/2019/09/config/certmanager" version="9.0.0"
    xmlns="http://holodeck-b2b.org/schemas/2019/09/config/certmanager">
    <xs:annotation>
        <xs:documentation>This XML schema defines the structure of the configuration file of the default <i>Certificate Manager</i> of Holodeck B2B.
        It configures the access to the three key stores of the Certificate Manager and includes two optional elements to configure OCSP revocation
        checks and "direct trust" in trading partner certificates.</xs:documentation>
        <xs:documentation>In version 7.0.0 the type attribute was added to the Password element to enable retrieving the password from a Java system 
        property or system environment variable.</xs:documentation>
        <xs:documentation>In version 8.0.0 the Certificate Manager also performs the validation of TLS certificates. To facilitate this, a configuration
        option has been added to specify whether the CA certificates included in the JRE's default trust store should be used when validating certificates.
        </xs:documentation>
        <xs:documentation>In version 9.0.0 the revocation check configuration is extended so it can be set to mandatory, optional and never. The default
        also has been changed to optional.</xs:documentation>
    </xs:annotation>
    <xs:element name="CertManagerConfiguration" type="CertManagerConfigurationType"/>
    <xs:complexType name="CertManagerConfigurationType">
        <xs:sequence>
            <xs:element name="PerformRevocationCheck" type="revocation-options" minOccurs="0"
                default="optional">
                <xs:annotation>
                    <xs:documentation>This OPTIONAL element indicates whether the Certificate Manager should perform a revocation check when
        			 validating trust in a certificate path. Possible settings are:<ul>
        			 <li>"mandatory" : revocation checks MUST be executed. If the revocation check cannot be performed because the certificate to 
        			         check does not contain the required extensions or the revocation data cannot be retrieved this will lead to 
        			         rejection of the certificate path being checked.</li>
        			 <li>"optional" : revocation checks SHOULD be executed, but if they cannot be executed the certificate path is "trusted with 
        			         warnings"</li>
        			 <li>"never" : revocation checks ARE NOT executed, only the correctness and validity (in terms of time) of the certificate 
        			         path is checked.</li></ul>
        			 </xs:documentation>
                    <xs:documentation>The default is value is <i>optional</i> so certificates are checked for revocation if possible, but
                     validation will not fail if revocation checks are not possible.</xs:documentation>
                    <xs:documentation>The enumeration is new in version 9.0.0 and for backward compatibility the values <i>true</i> and <i>false</i> 
                        are still accepted and mapped to <i>optional</i> resp <i>never</i>. These values however are <b>deprecated</b> and SHOULD NOT
                        be used any more.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="DirectTrustPartnerCertificates" type="xs:boolean" minOccurs="0"
                default="false">
                <xs:annotation>
                    <xs:documentation>This OPTIONAL element indicates whether the Certificate Manager should use the trading partner certificate as
        			 as trust anchors when validating trust in a certificate (path).</xs:documentation>
                    <xs:documentation>The default value <i>false</i> results in the same behaviour as in version 4.x. Setting the value to <i>true</i>
        			 results in the same behaviour as in version 3 and before. The default is considered safer as the correct issuing of the certificates
        			 will be checked. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="IncludeDefaultTrustStore" type="default-trust-options" minOccurs="0"
                default="tlsOnly">
                <xs:annotation>
                    <xs:documentation>This OPTIONAL element indicates whether the Certificate Manager should include the certificates of the well-known
        			 and generically trusted Certificate Authorities as stored in the Java runtime's default trust store for the trust validation of
        			 certificates.</xs:documentation>
                    <xs:documentation>The default value <i>tlsOnly</i> results in the same behaviour as in previous versions where the default trust
        			 store is only used for the validation of TLS certificates.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Keystores" type="KeystoresType">
                <xs:annotation>
                    <xs:documentation>This element contains the information needed to access the three JKS key stores used by Holodeck B2B's default Certificate Manager.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="revocation-options">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mandatory"/>
            <xs:enumeration value="optional"/>
            <xs:enumeration value="never"/>
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="default-trust-options">
        <xs:restriction base="xs:string">
            <xs:enumeration value="never"/>
            <xs:enumeration value="tlsOnly"/>
            <xs:enumeration value="mlsOnly"/>
            <xs:enumeration value="always"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="KeystoresType">
        <xs:sequence>
            <xs:element name="PrivateKeys" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding the private keys and related certificates that are used for signing and decrypting of messsages. 
                    Note that a key pair may need to contain more than  one certificate if a certificate chain needs to be included in a signature.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TradingPartnerCertificates" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding the certificates with the public keys used for encryption of messages.
                    Note that the certificates contained in this key store also act as "trust anchor" when "direct trust" is enabled.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TrustedCertificates" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding "trust anchors" certificates used for trust validation of certificates used to sign messages.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KeystoreAccessType">
        <xs:sequence>
            <xs:element name="Path" type="non-empty-string">
                <xs:annotation>
                    <xs:documentation>The path of the Java key store. A relative path is will start at the Holodeck B2B home directory (see org.holodeckb2b.interfaces.config.IConfiguration.getHolodeckB2BHome())</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="Password" type="PasswordType">
                <xs:annotation>
                    <xs:documentation>The password to access the key store. When the type attribute is set to "sys" or "env" the password is retrieved
                    from the runtime context, i.e. a Java system property ("sys") or operating system environment variable ("env"). The value of the
                    element in these cases must include the name of the property or environment variable to use.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PasswordType">
        <xs:simpleContent>
            <xs:extension base="non-empty-string">
                <xs:attribute name="type" default="literal">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="literal"/>
                            <xs:enumeration value="sys"/>
                            <xs:enumeration value="env"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="non-empty-string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== holodeck-b2b/Holodeck-B2B/modules/holodeckb2b-distribution/basedir/conf/certmanager_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- =====================================================================================

             Holodeck B2B Default Certificate Manager Configuration

This file configures the access to the keystores used by the default implementation
of the Certificate Manager to store the key pairs and certificates needed in the 
processing of the messages. It uses three  JKS keystores which contain the keys and 
certificates needed in specific actions:
* The key pairs used for signing and decrypting messages and to use for TLS client 
  authentication. Note that a key pair may need to contain more than one certificate if 
  a certificate chain needs to be included in a signature or TLS handshake.
* The trading partner certificates with public keys used for encryption of messages and 
  identification.
* Holding "trust anchors" used for trust validation of certificates used to sign messages
  and to validate TLS server certificates. Normally these are the certificates of trusted 
  Certificate Authorities. 

Since TLS certificates are often issued by one of the common and well-known Certificate 
Authorities the default Certificate Manager implementation also uses the JVM default
trust store for trust validation of TLS certificates. The use of this default trust store
can be fine tuned by the <i>IncludeDefaultTrustStore</i> parameter. 
As in some environments the certificates of trading partner are directly trusted the 
<i>direct trust</i> mode can be enabled in which case the trading partner certificates 
are handled like trust anchors, with the exception that they are checked for validity. 
<p>Another feature of this Certificate Manager is the option to perform a revocation 
check on certificates. This check is disabled by default for back-ward compatibility and 
can be enabled in the configuration. Note however that when enabled and used in an 
environment where certificates don't provide revocation information this will result 
in a lot of rejections (if set to <i>mandatory</i>) or 
<code>ISignatureVerifiedWithWarning</code> events as the revocation check could not be 
executed (if set to <i>optional</i>).
===================================================================================== -->
<CertManagerConfiguration xmlns="http://holodeck-b2b.org/schemas/2019/09/config/certmanager"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://holodeck-b2b.org/schemas/2019/09/config/certmanager ../repository/xsd/hb2b-certmanager-cfg.xsd">
    <!-- 
        The value set in the PerformRevocationCheck element specified whether 
        the Certificate Manager should perform a revocation check when
        validating trust in a certificate path. 
        Possible settings are:<ul>
        <li>"mandatory" : revocation checks MUST be executed. If the revocation check cannot 
                be performed because the certificate to check does not contain the required 
                extensions or the revocation data cannot be retrieved this will lead to 
                rejection of the certificate path being checked.</li>
        <li>"optional" : revocation checks SHOULD be executed, buf if they cannot be executed 
                the certificate path is "trusted with warnings"</li>
        <li>"never" : revecocation checks ARE NOT executed, only the correctness and validaty 
                (in terms of time) of the certificate path is checked.</li>
        </ul>
        For backward compatibility the default setting is "never". 
    -->
    <PerformRevocationCheck>never</PerformRevocationCheck>
    <!--
    <DirectTrustPartnerCertificates>false</DirectTrustPartnerCertificates>        
    -->
    <!--
        The value set in the IncludeDefaultTrustStore element defines how the 
        Certificate Manager uses the JVM default trust store when validating
        the trust of certificates. The possible values are:
        - never : don't use the default trust store at all. You must ensure
            the trusted CA's are imported in the Certificate Manager's trust
            store.
        - tlsOnly : use the default trust store only for validation of 
            TLS certificates
        - mlsOnly : use the default trust store only for validation of 
            certificates used to sign messages
        - always : always use the default trust store
        NOTE: When used, the certificates in default trust store are added to
            the certificates included in the Certificate Manager's trust store  
    -->
    <!--
    <IncludeDefaultTrustStore>tlsOnly</IncludeDefaultTrustStore>
    -->    
    <Keystores>
        <PrivateKeys>
            <Path>repository/certs/privatekeys.jks</Path>
            <Password>secrets</Password>
        </PrivateKeys>
        <TradingPartnerCertificates>
            <Path>repository/certs/partnerkeys.jks</Path>
            <Password>nosecrets</Password>
        </TradingPartnerCertificates>
        <TrustedCertificates>
            <Path>repository/certs/trustedcerts.jks</Path>
            <Password>trusted</Password>
        </TrustedCertificates>
    </Keystores>
</CertManagerConfiguration>
